---

- name: Update packages
  apt:
    name: "*"
    state: latest
  become: true

- name: Install nginx
  apt:
    name: nginx

- name: Change nginx main page
  copy:
    src: index.html
    dest: /var/www/html/index.html
