---

- name: Install nginx
  package:
    name: nginx

- name: Change nginx main page
  copy:
    src: index.html
    dest: /var/www/html/index.html

- name: Change nginx config
  copy:
    src: default
    dest: /etc/nginx/sites-enabled/
  notify:
    - Restart nginx

- name: Start and enable nginx (always needed)
  service:
    name: nginx
    state: started
    enabled: yes

