- name: add grafana gpg key
  apt_key:
    url: https://packages.grafana.com/gpg.key

- name: add grafana rep
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main

- name: Install grafana
  apt:
    name: grafana

- name: Change grafana config
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify:
    - Restart grafana

#CONFIGURE GRAFANA DASHBOARDS AND DATASOURCES

- name: Configure Prometheus as default datasource
  template:
    src: prometheus_ds.yaml.j2
    dest: /etc/grafana/provisioning/datasources/prometheus.yaml
  notify:
    - Restart grafana

- name: Grafana dashboard directory
  file:
    path: /var/lib/grafana/dashboards
    state: directory
    owner: grafana
    group: grafana

- name: Add grafana dashboards (newer version from slides)
  copy:
    src: "{{ item }}.json"
    dest: "/var/lib/grafana/dashboards/{{ item }}.json"
    owner: grafana
    group: grafana
  loop:
    - main
    - test

#LOGGING INFLUX RELATED

- name: Configure Influx-Latency datasource
  template:
    src: influx_latency_ds.yaml.j2
    dest: /etc/grafana/provisioning/datasources/influx_latency_ds.yaml
  notify:
    - Restart grafana

- name: Configure Influx-Telegraf datasource
  template:
    src: influx_telegraf_ds.yaml.j2
    dest: /etc/grafana/provisioning/datasources/influx_telegraf_ds.yaml
  notify:
    - Restart grafana

- name: Start and enable grafana
  service:
    name: grafana-server
    state: started
    enabled: yes
