---

- name: Install uwsgi
  apt:
    name: 
      - uwsgi
      - uwsgi-plugin-python3

- name: Start and enable uwsgi
  service:
    name: uwsgi
    state: started
    enabled: yes

#Copy module takes src from files folder, template takes from templates folder
- name: Copy to
  template:
    src: agama.ini 
    dest: /etc/uwsgi/apps-enabled/
  notify:
    - Restart uwsgi


#Handlers are used only in the end if there are any conf changes, if not they are not used
