---
- name: Init
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - init

- name: Node Exporter for main monitoring
  hosts: all
  become: yes
  roles:
    - node_exporter
  tags: node

# ===== DNS Setup =====

- name: Bind9
  hosts: dns_servers
  become: yes
  roles:
    - bind
    - bind_exporter
  tags: bind

- hosts: prometheus
  become: yes
  gather_facts: yes
  roles:
    - prometheus
  tags: prom

- name: Mysql
  hosts: app_stack
  become: yes
  roles:
    - mysql
    - mysql_exporter
  tags: mysql

- name: Nginx at App Stack
  hosts: app_stack
  become: yes
  roles:
    - nginx
    - nginx_exporter
  tags: nginx

- name: Grafana
  hosts: grafana
  become: yes
  roles:
    - grafana
  tags: graf
