---
- hosts: all
  roles:
    - node_exporter

- hosts: prometheus
  become: yes
  gather_facts: yes
  roles:
    - init
    - bind
    - nginx
    - prometheus
  tags: prom

- name: web
  hosts: prometheus
  become: yes
  roles:
    - nginx
  tags: nginx

- name: debug
  hosts: all
  gather_facts: yes
  tasks:
    - debug:
        var: hostvars['remote2']['ansible_facts']['default_ipv4']['address']
  tags: debug
