---
- name: Init
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - init
  tags: always
  #tags:always always runs that role

- name: Run rsyslog task on all hosts
  hosts: all
  become: yes
  roles:
    - rsyslog
  tags: rsyslog

- name: Node Exporter for main monitoring
  hosts: all
  become: yes
  roles:
    - node_exporter
  tags: node

- name: Backup
  hosts: all
  become: yes
  roles:
    - backup
  tags: backup

- name: Docker for hejoes-1 and hejoes-2
  hosts: app_stack
  become: yes
  roles:
    - docker
  tags: docker

# ===== DNS =====

- name: Bind9
  hosts: dns_servers
  become: yes
  roles:
    - bind
    - bind_exporter
  tags: bind

# ===== App Stack (hejoes-1 and hejoes-2) =====
- name: MySQL
  hosts: app_stack
  become: yes
  roles:
    - mysql
    - mysql_exporter
    - mysql_backup
  tags: mysql

- name: Nginx at App Stack
  hosts: app_stack
  become: yes
  roles:
    - nginx
    - nginx_exporter
  tags: nginx

- name: Agama
  hosts: app_stack
  become: yes
  roles:
    - agama
  tags: agama

- name: Keepallived
  hosts: app_stack
  become: yes
  roles:
    - keepalived
    - keepalived_exporter
  tags: keepalived

- name: Haproxy
  hosts: app_stack
  become: yes
  roles:
    - haproxy
    - haproxy_exporter
  tags: haproxy

# ===== Other Parts =====

- name: prometheus
  become: yes
  hosts: prometheus
  roles:
    - prometheus
  tags: prometheus

- name: Install grafana
  hosts: grafana
  become: yes
  roles:
    - grafana
  tags: grafana

- name: InfluxDB
  hosts: influx
  become: yes
  roles:
    - influxdb
    - influxdb_exporter
    - pinger
  tags: influx

- name: Influxdb Backup
  hosts: influx
  become: yes
  roles:
    - influxdb_backup
  tags: influxdb_b
