---
- name: Init 
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - init
  tags: init

- name: Run rsyslog task on all hosts
  hosts: all
  become: yes
  roles:
  - rsyslog
  tags: rsyslog

- name: Node Exporter for main monitoring
  hosts: all
  become: yes
  roles:
    - node_exporter
  tags: node

- name: Backup 
  hosts: all
  become: yes
  # And manually have to change file permissions
  roles:
    - backup
  tags: backup

- name: Docker (only needs 1hosts where grafana is)
  hosts: grafana
  become: yes
  roles:
    - docker
  tags: docker

- name: Agama and uwsgi
#lets put agama to only hejoes-1, where nginx is so to not get repeated ids in mysql replication
  hosts: agama
  become: yes
  roles:
    - agama
    - uwsgi
  tags: agama

# ===== DNS Setup =====

- name: Bind9
  hosts: dns_servers
  become: yes
  roles:
    - bind
    - bind_exporter
  tags: bind

- name: Nginx at App Stack
  hosts: web_server
  become: yes
  roles:
    - nginx
    - nginx_exporter
  tags: nginx

- hosts: prometheus
  become: yes
  hosts: prometheus
  roles:
    - prometheus
  tags: prom

- name: Mysql
  hosts: db_servers
  become: yes
  roles:
    - mysql
    - mysql_exporter
  tags: mysql

- name: Install grafana
  hosts: grafana
  become: yes
  roles:
    - grafana
  tags: grafana

- name: InfluxDB
  hosts: influx
  become: yes
  roles:
    - influxdb
    - influxdb_exporter
    - pinger
  tags: influx

- name: Influxdb Backup
  hosts: influx
  become: yes
  roles:
    - influxdb_backup
  tags: influxdb_b

- name: mysql backup
  hosts: app_stack
  become: yes
  roles:
    - mysql_backup
  tags: mysql_b