{
 "title": "Main2",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Keepalived VRPP (Remote1)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=\"remote1:9165\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Keepalived VRPP (Remote2)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{instance=\"remote2:9165\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HAProxy Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Nginx Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "InfluxDB health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bind9 Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HAProxy Servers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_server_up", "legendFormat": "{{instance}} {{server}}" }
   ]
  },
  {
   "title": "Bind9 Master",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{instance=\"remote3:9119\", type=\"A\"}[1m])"
    }
   ]
  },
  {
   "title": "Bind9 Slave",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{instance=\"remote1:9119\", type=\"A\"}[1m])"
    },
    {
     "expr": "rate(bind_resolver_queries_total{instance=\"remote2:9119\", type=\"A\"}[1m])"
    }
   ]
  },
  {
   "title": "InfluxDB write rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(influxdb_write_write_ok[1m])"
    }
   ]
  },
  {
   "title": "Pinger",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dst" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rtt",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 13 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total[5m])"
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[5m])"
    }
   ]
  },
  {
   "title": "Memory load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total[10m])"
    }
   ]
  }
 ]
}