{
 "title": "Main",
 "time": { "from": "2022-10-22T08:39:35.547Z", "to": "2022-10-22T10:39:35.547Z" },
 "panels": [
  {
   "title": "Nginx requests per minute [3]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[3m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bind9 status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Mysql status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Nginx status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "InfluxDB health",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 5 },
   "targets": [
    {
     "expr": "rate(influxdb_exporter_stats_query_success[3m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "InfluxDB write rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 5 },
   "targets": [
    {
     "expr": "rate(influxdb_write_write_ok[3m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DNS (Bind) queries per minute [3]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total[3m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total[10m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mysql selects per minute [3]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total[3m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 9, "y": 18 },
   "targets": [
    {
     "expr": "1- rate(node_cpu_seconds_total{mode=\"idle\"}[1m])",
     "legendFormat": "__auto"
    },
    { "legendFormat": "{{instance}}" }
   ]
  }
 ]
}