- name: Add user agama
  user:
    name: agama

- name: Create directory /opt/agama
  file:
    path: /opt/agama
    owner: agama
    state: directory

- name: Install the dependencies required
  apt:
    name:
      - python3-flask-sqlalchemy
      - python3-pymysql

- name: Download agama
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama
