---

- name: Add Agama user
  user: 
    name: agama

- name: Create directory 
  file:
    path: /opt/agama
    state: directory
    owner: agama

- name: Install dependencies
  apt:
    name:
      - python3-flask-sqlalchemy
      - python3-pymysql

- name: Install agama.py
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama
