---

#This role just updates packages so i would not get any dependency not found error in future.

- name: Update packages
  become: yes
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
