- name: Create .ssh directory
  file:
    path: /home/backup/.ssh
    state: directory

- name: Create backup user
  user:
    name: backup
    home: /home/backup
    generate_ssh_key: yes
    ssh_key_file: /home/backup/.ssh/id_rsa

- name: Copy known hosts file
  template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
