- name: Create .ssh directory
  file:
    path: /home/backup/.ssh
    state: directory

- name: Create backup user
  user:
    name: backup
    home: /home/backup
    generate_ssh_key: yes
    shell: /bin/bash #without shell wont be able to login as backup user
    ssh_key_file: /home/backup/.ssh/id_rsa

- name: Change /home/backup folder permissions
#So that i dont get .cache folder not found
  file:
    path: "{{ item }}"
    owner: backup
    group: backup
  loop:
    - /home/backup
    - /home/backup/.ssh

- name: Copy known hosts file
  template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup

- name: Create restore directories
  file:
    path: /home/backup/restore/{{ item }}
    state: directory
    mode: 0755
    owner: backup
  loop:
    - mysql
    - influxdb

- name: Install duplicity
  apt:
    name: duplicity
