- name: Create influxdb backup directory
  file:
    path: /home/backup/influxdb
    state: directory
    mode: 0755
    owner: backup

- name: Copy crontab file
  template:
    src: influxdb-backup.j2
    dest: /etc/cron.d/influxdb-backup
