- name: Install mysqld exporter
  apt:
    name:
      - prometheus-mysqld-exporter

- name: MySQL user for mysql exporter
  community.mysql.mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    host: "%"
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: yes

- name: Change mysql config
  template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
  no_log: yes
  notify:
    - Restart mysql exporter

- name: Pause for 10 seconds
  pause:
    seconds: 10

- name: Copy prometheus-mysqld-exporter file
  copy:
    src: prometheus-mysqld-exporter
    dest: /etc/default/prometheus-mysqld-exporter
  notify:
    - Restart mysql exporter

- name: Start and enable mysql exporter
  service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes
