- name: Install MySQL
  apt:
    name: mysql-server

- name: Install pymysql
  apt:
    name: python3-pymysql

- name: Change MySQL config
  template:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify:
   - Restart mysql

- name: Restart mysql
#Needed because otherwise my agama wont start up, cause agama will not read override.conf bind-address 0.0.0.0 without manual restart of mysql
  service:
    name: mysql
    state: restarted

- name: Start the MySQL service and enable it
  service:
    name: mysql
    state: started
    enabled: yes

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user - agama
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock