- name: Install MySQL
  apt:
    name: mysql-server

- name: Install pymysql
  apt:
    name: python3-pymysql

- name: Change MySQL config
  template:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify:
    - Restart mysql

#- name: Restart mysql
#Needed because otherwise my agama wont start up, cause agama will not read override.conf bind-address 0.0.0.0 without manual restart of mysql
#service:
#name: mysql
#state: restarted

- name: Start the MySQL service and enable it
  service:
    name: mysql
    state: started
    enabled: yes

- name: MySQL database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify:
    - Reset MySQL source
    - Reset MySQL replica

- name: MySQL user - agama
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: MySQL replication user
  mysql_user:
    name: "{{ mysql_repl_user }}"
    password: "{{ mysql_repl_password }}"
    host: "%"
    priv:
      "*.*": "REPLICATION SLAVE"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true

- name: MySQL replica read only
  mysql_variables:
    variable: read_only
    value: "{{ 'OFF' if hostvars[inventory_hostname]['ansible_default_ipv4']['address'] == mysql_host else 'ON' }}"
    mode: persist
    login_unix_socket: /var/run/mysqld/mysqld.sock
  notify:
    - Reset MySQL source
    - Reset MySQL replica
