---

- name: Adds Juri
  user: 
    name: juri

- name: Get "Juri" keys
  ansible.posix.authorized_key:
    user: juri
    key: https://github.com/hudolejev.keys

- name: Adds Roman
  user: 
    name: roman

- name: Add "Roman" keys
  ansible.posix.authorized_key:
    user: roman
    key: https://github.com/romankuchin.keys
