- name: Add user "pinger"
  ansible.builtin.user:
    name: pinger

- name: Install fping
  apt:
    name: fping

- name: Create pinger directory
  file:
    path: /etc/pinger
    state: directory
    mode: 0755

- name: Copy pinger shell file
  copy:
    src: pinger.sh
    dest: /usr/local/bin/pinger
    mode: a+x

- name: Copy pinger service file
  copy:
    src: pinger.service
    dest: /etc/systemd/system/pinger.service
    mode: 0644
  notify:
    - Reload systemd

- name: Copy pinger config
  template:
    src: pinger.conf.j2
    dest: /etc/pinger/pinger.conf
  notify:
    - Restart pinger

- name: Start and enable pinger
  service:
    name: pinger
    state: started
    enabled: yes
