- name: Install prometheus
  apt:
    name: prometheus

- name: Add prometheus ARGS
  ansible.builtin.template:
    src: prometheus
    dest: /etc/default/prometheus
  notify:
    - restart prometheus

- name: Add prometheus yml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify:
    - restart prometheus

- name: Start and enable prometheus
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: yes
