- name: Install docker
  apt:
    name:
      - docker.io
      - python3-docker  
#python3-docker package allows ansible to manage Docker resources. Need it for ansible to perform tasks.

- name: Start and enable docker
  service:
    name: docker
    state: started
    enabled: yes